### ISSUE TITLE
doesn't work on mac

### ISSUE THREAD

**Issue by haiaty** [jetli/create-yew-app#7]
Hi, 
I'm using a mac and I have tried to use the package but after I cloned it, I ran

`npm start`

and I got the following error:

> /Users/haiaty/Code/rust_projects/my-app/node_modules/parcel-plugin-wasm.rs/wasm-loader.js:2:14: Cannot resolve dependency './yew_app_bg.js' at '/Users/haiaty/Code/rust_projects/my-app/node_modules/parcel-plugin-wasm.rs/yew_app_bg.js'
>   1 | var wasm;const __exports = {};
> > 2 | export * from "./yew_app_bg.js";
>     |              ^
>   3 | 
>   4 |       function init(wasm_path) {
>   5 |           const fetchPromise = fetch(wasm_path);

What could be the issue?

**Comment by jetli** [comment]
did you run `npx create-yew-app my-app` to create a new app,  or just clone this repo and run `npm start` ?
if you clone this repo, you should run `npm install` first and then run `npm start`, please see https://github.com/jetli/create-yew-app/tree/master/crates/yew-app#readme

**Comment by Voronar** [comment]
Maybe blocked by https://github.com/catsigma/parcel-plugin-wasm.rs/issues/30

**Comment by Voronar** [comment]
Temporary webpack alternative: https://github.com/yewstack/yew-wasm-pack-template

**Comment by jetli** [comment]
Previously I found webpack is very slow for Rust/Wasm when hot reloading, it's unbearable slow for a just medium size project like https://github.com/jetli/rust-yew-realworld-example-app,  so finally I've chosen parcel for bundling.

**Comment by haiaty** [comment]
> did you run `npx create-yew-app my-app` to create a new app, or just clone this repo and run `npm start` ?
> if you clone this repo, you should run `npm install` first and then run `npm start`, please see https://github.com/jetli/create-yew-app/tree/master/crates/yew-app#readme

I have installed it and ran 'npm start' . Then I tried to 'npm install' but it doesn't work

**Comment by swstegall** [comment]
I tried doing the same thing on Windows 10 and have been having the same sort of trouble. Windows doesn't like using environment variables in-line like you're using them, so I had to add another script to `crates\yew-app\package.json` called `set-dev` that uses windows `set` command, then another script, `start-win` that chains this into the start command.

Alas, after doing these things, I encountered the same error that @haiaty experienced. This can be fixed with the temporary fix mentioned in the link posted by @Voronar, catsigma/parcel-plugin-wasm.rs#30. To fix this issue with the current codebase if you're working with the project locally, do the following:

1. Open `crates\yew-app\Cargo.toml`.
2. Edit `wasm-bindgen` to `wasm-bindgen = "0.2, <0.2.61"`.

You should now be able to do `npm start` and have the project work.

**Comment by jetli** [comment]
temp fix by `wasm-bindgen = "0.2, <0.2.61"`

**Comment by jetli** [comment]
Fixed by https://github.com/jetli/create-yew-app/pull/11

**Comment by patientplatypus6** [comment]
This isn't fixed - have same error.
